### PR TITLE
updated the pre-commit configuration

### PR DESCRIPTION
**Pull request by Anu-Ra-g**
This PR contains new pre-commit configuration.

### CODE REVIEW

**Comment by martindurant** [comment]
PR #64 is blocked until this is merged, so would appreciate someone having a look here.

**Comment by martindurant** [comment]
Thanks @norlandrhagen .

**Comment by martindurant** [comment]
(I can access the file from local now, so it might have been an intermittent network effect)

**Comment by Anu-Ra-g** [comment]
@martindurant The same issue has also been raised here in #61. I'm running the notebook associated with this error.

**Comment by martindurant** [comment]
NoCredentials implies that it is trying to authenticate - but the data is public, so anon=True should be in the remote_options.

**Pull request merged**
